### ISSUE TITLE
Bug: very rare crash

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Almeros/android-gesture-detectors#15]
Not sure what I've done to do it, other than playing with it.

This is what I got in the logs:

  java.lang.IllegalArgumentException: pointerIndex out of range
            at android.view.MotionEvent.nativeGetAxisValue(Native Method)
            at android.view.MotionEvent.getX(MotionEvent.java:1983)
            at com.almeros.android.multitouch.TwoFingerGestureDetector.updateStateByEvent(TwoFingerGestureDetector.java:77)
            at com.almeros.android.multitouch.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:136)
            at com.almeros.android.multitouch.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:66)

**Comment by Almeros** [comment]
I'm closing this one since it doesn't look like others have had the same problem and you are not giving us a lot of info about the problem :)

**Comment by AndroidDeveloperLB** [comment]
That's because this is all i had.

**Comment by androidapkr** [comment]
Need Help in

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2136)
       at com.rahul.mystickers.multitouch.TwoFingerGestureDetector.updateStateByEvent(TwoFingerGestureDetector.java:76)
       at com.rahul.mystickers.multitouch.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:138)
       at com.rahul.mystickers.multitouch.BaseGestureDetector.handleInProgressEvent(BaseGestureDetector.java:4)
       at com.rahul.mystickers.multitouch.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:66)

**Comment by Almeros** [comment]
@AndroidDeveloperLB and @androidapkr It would really help if you explained at what time this happens, how do you use the framework, what do you do at the point this occurs... did you debug with a debugger? Can you get more info through logging (just before this happens)?

**Comment by AndroidDeveloperLB** [comment]
@Almeros Already explained at what time and what I did till it happened (just playing with it). 
Sadly this was a long time ago, and the repository doesn't have a sample, so I can't try again to reproduce it.
If you have a working sample, please share it and I will try again.

**Comment by Almeros** [comment]
@AndroidDeveloperLB OK, well it just gets very hard to find out what causes the bug then I'm afraid :(

Check out https://github.com/Almeros/android-gesture-detectors-example for a working example

**Comment by AndroidDeveloperLB** [comment]
OK tried the sample. Can't reproduce. Have the library changed since the report?
Why handle it after 3 years... I can't remember this far...
Even the first reply was after 2 years.

**Comment by AndroidDeveloperLB** [comment]
Also, I suggest putting the sample with the library. Most repositories do it, as it makes it easier to try it out.
