### ISSUE TITLE
Still : Pointer Index out of range

### ISSUE THREAD

**Issue by androidapkr** [Almeros/android-gesture-detectors#35]
Rare but often bug which is crash app 

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2136)
       at com.rahul.mystickers.multitouch.TwoFingerGestureDetector.updateStateByEvent(TwoFingerGestureDetector.java:76)
       at com.rahul.mystickers.multitouch.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:138)
       at com.rahul.mystickers.multitouch.BaseGestureDetector.handleInProgressEvent(BaseGestureDetector.java:4)
       at com.rahul.mystickers.multitouch.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:66)

**Comment by Almeros** [comment]
I'm sorry, I can see from the stacktrace this is in your own code (see package name: com.rahul.mystickers.multitouch.*). From the stacktrace it can't be seen if you adjusted code and what it is that you adjusted...
