### ISSUE TITLE
TwoFingerGestureDetector : IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by riggaroo** [Almeros/android-gesture-detectors#39]
We are getting this crash in the TwoFingerGestureDetector.

```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2379)
       at com.almeros.android.multitouch.TwoFingerGestureDetector.updateStateByEvent(TwoFingerGestureDetector.java:77)
       at com.almeros.android.multitouch.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:136)
       at com.almeros.android.multitouch.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:66)
```

**Comment by Almeros** [comment]
Can you elaborate a bit more on when and how you get this (how to reproduce)? 

Looks like somehow getX(...) can't find the pointerIndex of value '1' it's given here, which is strange when the 'Two'FingerGestureDetector is used. So, perhaps you are moving a finger/pointer out of the screen when this happens?
